language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: AUgq0NDCElcJcW6QRCqI8XG+avgN9kszzNkvsnXcB3a86a1te0RDfSTSiIPATTNgbC2J9ajmmziqAH5KGKyUbrkrxbvANZfDnjuvBXxTlHXzhevniRlaCKyzZtqCeaeRwemUS/HtB+YO0qb/s0q1/fR5CiCLn6MI6XY7fSUojyHBZS4Olnja/coRT9+dr/PEfK9N+nFYlep3RuBPOMLbyJgAP4SLfbotR8rezRZ1kbpz1VrnBr5qFpsSzlV6e5yI6gZXOUao0Op24zslAbm4Ibt4MSeRJ/VjWECLo7wITuYCiHnBz5p2lqska6vNoFoxdLb8/T7RKgFWA9OG149SbqGLUihxLcediFBgHq4gJK1FQ8T8kLip/9ZdenRsy6YF6Xz9YuQzU1xWM8UfaunpMkMwlSyQce50ZH3RRNNqRW4WGYOY1act67CyDiU+ngnQeJfo9gga/y3o66vkA01xNaLc9BM6RoWnDbJXic3rPz1shLrvQbaLmE7Il3OO/JvgRay9KaOQrQFRS+bhdnsCDMPkWlGER47WZyiQcC8E7Jzy6eVIxyxmnmSCpxg0tu4mMz3381yw8j2TowMw9SAtRou2po8fpMD+4jQmmhjqD3ccTxqhtOQ/ewFuWAtBQgYKM3rebOEH1jqV939oC+mngP1oLFaRG7EYHWaTT/dxWmA=
  app: news-srr
  on:
    repo: sivasankar9/psxt
  skip_cleanup: 'true'
