language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: bTKMzPV2FFHeIb+FFaWgFhpOU/PH01BS5yvaE3RBznenGz5QDta5EDqFbCtpVm9k2IfOOfrSciFeqXXqME718XIzTRsr/DUY+4Dl4R34m/96jE/MVsNhyhMc7Lc3N/FDv94m89cCEzH+YdSp8Pu8xi4LGI53KlHj0r6o4YGRFLu3oP2S+POGFx9gkLW+DANRKrWh2hqI5F61pplviGweDqPStz42GJI+X207pAOJ6rftPJmkZKuAQ0+dnRnNXX83rdbUfEzv31PPuImXMn67fL573iWgN1/IBcMsbAyZ279gM2xqP+bpQP2krcCYWTffSm6Rre1BxyjKjAMO7lsASEQGLvJej+iRIMp4VG1BKs/jnPOrTcmtHG9h8ZUf4VOkFVcPsHUvFIjWObAqf9c0eRIY1rbXf2vYLCOvpLisdCHfml4qOJ5dWLlGjyniMbQVRaCxmpy6fudRhLJpaMBHWIUTpis2aukljRlFItnMoeo7ZzVQDxVU/Eu2FZCR+EqczHQPad+3e9JzVmlHdBK1MzpdiVQwOH2Ih9WVJadgpLxi02letj8P02ONAzvBXzvRf5yJt7wA+2XxQvsw+9b6Ti/nzWfIq4+Rb0wuinwLyY04++EQ58dVLAPB5O2zIGE58GbdyHzRvP/AkAWA8AGDIHor4SYCnXcOWPXHjVw/HgU=
  app: news-srr
  on:
    repo: sivasankar9/psxt
  skip_cleanup: 'true'
